import type { Listing } from "@/app/types/listing";

// GCFIRY65OQE7DFP5KLNS2PF2LVZMUZYJX4OZIEQ36N2IQANUB5XVYOJR is the demo host wallet.
// It is a valid Stellar Ed25519 public key (deterministic seed = 0x01*32).
// Connect this address in Freighter to access the Host Dashboard.
export const DEMO_HOST_WALLET = "GCFIRY65OQE7DFP5KLNS2PF2LVZMUZYJX4OZIEQ36N2IQANUB5XVYOJR";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "listing-1",
    roomId: "1001",
    ownerWallet: DEMO_HOST_WALLET,
    escrowAmount: "125000000",
    nightlyPriceXlm: 12.5,
    title: "Amalfi Glass Villa",
    location: "Amalfi Coast, Italy",
    description: "Clifftop villa with panoramic sea views, private infinity pool, and direct access to the Mediterranean. Escrow-protected stay with verified host.",
    amenities: ["Infinity pool", "Sea view", "Private terrace", "Chef kitchen", "Concierge"],
    hostName: "Casa Meridian",
    hostSince: "2024",
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    availability: "Available",
    gradientFrom: "rgba(245,158,11,0.55)",
    gradientTo: "rgba(8,47,73,0.9)",
  },
  {
    id: "listing-2",
    roomId: "1002",
    ownerWallet: DEMO_HOST_WALLET,
    escrowAmount: "87500000",
    nightlyPriceXlm: 8.75,
    title: "Kyoto Garden Loft",
    location: "Higashiyama, Kyoto",
    description: "Traditional machiya townhouse with a private zen garden, tatami rooms, and walking distance to Gion. Fully verified on-chain reservation.",
    amenities: ["Zen garden", "Tatami rooms", "Tea ceremony", "Bicycle rental", "Onsen access"],
    hostName: "Higashiyama Stays",
    hostSince: "2023",
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    availability: "Available",
    gradientFrom: "rgba(167,139,250,0.5)",
    gradientTo: "rgba(30,27,75,0.9)",
  },
  {
    id: "listing-3",
    roomId: "1003",
    ownerWallet: DEMO_HOST_WALLET,
    escrowAmount: "70000000",
    nightlyPriceXlm: 7.0,
    title: "Lisbon Alfama Townhouse",
    location: "Alfama, Lisbon",
    description: "Restored 18th-century townhouse in the historic Alfama district. Azulejo-tiled interiors, rooftop terrace with castle views, and fado music nearby.",
    amenities: ["Rooftop terrace", "Castle view", "Historic district", "Wine cellar", "Parking"],
    hostName: "Alfama Heritage",
    hostSince: "2024",
    maxGuests: 5,
    bedrooms: 2,
    bathrooms: 2,
    availability: "Available",
    gradientFrom: "rgba(251,146,60,0.5)",
    gradientTo: "rgba(67,20,7,0.9)",
  },
  {
    id: "listing-4",
    roomId: "1004",
    ownerWallet: DEMO_HOST_WALLET,
    escrowAmount: "200000000",
    nightlyPriceXlm: 20.0,
    title: "Swiss Alpine Chalet",
    location: "Grindelwald, Switzerland",
    description: "Luxury ski-in/ski-out chalet with Eiger views, private sauna, and a dedicated concierge. Escrow deposit held until checkout confirmation.",
    amenities: ["Ski-in/ski-out", "Private sauna", "Mountain view", "Fireplace", "Concierge"],
    hostName: "Alpine Escrow Stays",
    hostSince: "2023",
    maxGuests: 8,
    bedrooms: 4,
    bathrooms: 3,
    availability: "Available",
    gradientFrom: "rgba(147,197,253,0.45)",
    gradientTo: "rgba(15,23,42,0.9)",
  },
  {
    id: "listing-5",
    roomId: "1005",
    ownerWallet: DEMO_HOST_WALLET,
    escrowAmount: "105000000",
    nightlyPriceXlm: 10.5,
    title: "Tulum Cenote Retreat",
    location: "Tulum, Mexico",
    description: "Eco-luxury villa steps from a private cenote. Thatched-roof palapa, outdoor shower, and jungle canopy views. Blockchain-verified reservation.",
    amenities: ["Private cenote", "Outdoor shower", "Jungle view", "Yoga deck", "Hammocks"],
    hostName: "Tulum Collective",
    hostSince: "2024",
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    availability: "Available",
    gradientFrom: "rgba(52,211,153,0.45)",
    gradientTo: "rgba(6,78,59,0.9)",
  },
  {
    id: "listing-6",
    roomId: "1006",
    ownerWallet: DEMO_HOST_WALLET,
    escrowAmount: "157500000",
    nightlyPriceXlm: 15.75,
    title: "Santorini Caldera Suite",
    location: "Oia, Santorini",
    description: "Cave-carved suite carved into the caldera cliff with a private plunge pool and unobstructed sunset views. Escrow-secured, no intermediaries.",
    amenities: ["Plunge pool", "Caldera view", "Cave architecture", "Sunset terrace", "Butler service"],
    hostName: "Oia Escrow Villas",
    hostSince: "2023",
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    availability: "Available",
    gradientFrom: "rgba(251,191,36,0.5)",
    gradientTo: "rgba(30,58,138,0.9)",
  },
];
